require("dotenv").config()
const express = require("express")
const app = express()
const cors = require("cors")
app.use(cors())
app.use(express.urlencoded({ extended: true }))
const inventory = require("./routes/inventoryRoute")
app.use("/store", inventory)
app.listen(process.env.PORT, () => { })