if (process.env.Node_ENV != "production") require("dotenv").config()
const express = require("express")
const app = express()
const cors = require("cors")
app.use(cors())
app.use(express.urlencoded({ extended: true }))
const inventory = require("./routes/inventoryRoute")
const user = require("./routes/userRoute")
app.get('/', (req, res) => {
    res.send('hello')
})

app.use("/store", inventory)
app.use("/user", user)
app.use(express.static('images'))
app.listen(process.env.PORT, () => { })